name: 📚 Themenbeitrag einreichen
description: Reiche einen neuen Themenbeitrag inkl. Aufgaben für das NADOO-Wiki ein
title: "[Beitrag] "
labels: ["themenbeitrag"]
body:
  - type: dropdown
    id: ap
    attributes:
      label: Abschlussprüfungsteil (AP)
      description: Zu welchem Teil der Abschlussprüfung gehört dein Beitrag?
      options: [ap1, ap2, bwl-recht-sicherheit]
    validations:
      required: true

  - type: input
    id: thema
    attributes:
      label: Thema (Slug)
      description: Slug für die spätere Datei und Ordnerstruktur, z. B. `versionsverwaltung`
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: Titel des Beitrags
    validations:
      required: true

  - type: textarea
    id: tags
    attributes:
      label: Tags
      placeholder: git, github, commit
    validations:
      required: true

  - type: textarea
    id: beschreibung
    attributes:
      label: Beitragstext (MDX)
    validations:
      required: true

  - type: textarea
    id: aufgaben
    attributes:
      label: Drei Aufgabenstellungen zum Beitrag
    validations:
      required: true

  - type: checkboxes
    id: einverstaendnis
    attributes:
      label: Lizenz
      options:
        - label: Ich stimme der Veröffentlichung unter MIT-Lizenz zu
          required: true