name: 📚 Themenbeitrag einreichen
description: Reiche einen neuen Themenbeitrag inkl. Aufgaben für das NADOO-Wiki ein
title: "[Beitrag] "
labels: ["themenbeitrag"]
body:
  - type: dropdown
    id: ap
    attributes:
      label: Abschlussprüfungsteil (AP)
      description: Zu welchem Teil der Abschlussprüfung gehört dein Beitrag?
      options:
        - ap1
        - ap2
        - bwl-recht-sicherheit
    validations:
      required: true

  - type: input
    id: thema
    attributes:
      label: Thema (Slug)
      description: Kurzer Slug für das Thema, z. B. `projektmanagement`, `softwareloesungen`
      placeholder: projektmanagement
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: Titel des Beitrags
      description: Klarer, sprechender Titel für das Thema
      placeholder: Projektmanagement in der Praxis
    validations:
      required: true

  - type: textarea
    id: tags
    attributes:
      label: Tags
      description: Kommagetrennte Liste von Tags
      placeholder: projektmanagement, netzplan, scrum
    validations:
      required: true

  - type: textarea
    id: beschreibung
    attributes:
      label: Beitragstext / Beschreibung
      description: Was soll inhaltlich im Beitrag enthalten sein? Skizziere kurz die geplanten Inhalte oder formuliere direkt den MDX-Inhalt.
      placeholder: |
        ## Einführung in das Projektmanagement  
        Ein Projekt ist ein einmaliges Vorhaben, das sich durch bestimmte Merkmale wie Zielvorgabe, zeitliche Begrenzung und Ressourcenbindung auszeichnet…

    validations:
      required: true

  - type: textarea
    id: aufgaben
    attributes:
      label: Aufgaben (3 Stück)
      description: Gib drei Aufgabenstellungen zum Thema an, idealerweise mit Ziel, Schwierigkeit oder Einsatzszenario.
      placeholder: |
        1. Beschreibe die Unterschiede zwischen dem Wasserfallmodell und Scrum anhand eines Beispiels.
        2. Erstelle einen Netzplan mit kritischem Pfad und Pufferzeitberechnung.
        3. Erkläre das SMART-Prinzip anhand einer eigenen Projektidee.

    validations:
      required: true

  - type: checkboxes
    id: einverstaendnis
    attributes:
      label: Einverständnis zur Veröffentlichung
      description: Ich bin damit einverstanden, dass mein Beitrag im Wiki unter MIT-Lizenz veröffentlicht wird.
      options:
        - label: Ja, ich stimme der Veröffentlichung zu
          required: true